site_name: far2l
site_url: https://far2l.github.io/

# Repository
repo_name: elfmz/far2l
repo_url: https://github.com/elfmz/far2l

nav:
  - 'Главная': 'index.md'
  - 'Установка': 'installation.md'
  - 'Первые шаги': 'getting-started.md'
  - 'Руководство пользователя':
    - 'Бекенды интерфейса': 'user-guide/backends.md'
    - 'Основные возможности': 'user-guide/features.md'
    - 'Комбинации клавиш': 'user-guide/keybindings.md'
    - 'Плагины':
      - 'Обзор плагинов': 'user-guide/plugins/index.md'
      - 'Работа с архивами (ArcLite)': 'user-guide/plugins/arclite.md'
      - 'Сетевые подключения (NetRocks)': 'user-guide/plugins/netrocks.md'
    - 'Макросы': 'user-guide/macros.md'
  - 'Сравнение':
    - 'far2l vs Midnight Commander': 'comparison/vs-mc.md'
    - 'far2l vs Windows FAR': 'comparison/vs-windows-far.md'
  - 'Решение проблем':
    - 'Конфликты горячих клавиш': 'troubleshooting/hotkey-conflicts.md'
    - 'Настройка терминалов': 'troubleshooting/terminal-setup.md'
    - 'Особенности Wayland': 'troubleshooting/wayland.md'
  - 'Для разработчиков':
    - 'Философия проекта': 'developer/philosophy.md'
    - 'Руководство для контрибьюторов': 'developer/contributing.md'

theme:
  name: material
  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
        - locale: ru
          default: true
          name: Russian
          build: true